name: Build Application

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'   
        
    - name: Install dependencies
      run: npm install   
      
    - name: Run tests
      run: npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run Snyk Docker vulnerability scan
      uses: snyk/actions/docker@v2
      with:
        image: my-app
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Set up SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        token: ${{ secrets.SONAR_TOKEN }}

    - name: Analyze code with SonarCloud
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my-app \
          -Dsonar.organization=my-organization \
          -Dsonar.sources=src \
          -Dsonar.host.url=https://sonarcloud.io

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Push Docker image
      run: |
        docker push my-app
        
